version: "3.10"
services:
  web:
    build: .
    image: aapq/photoshnaya_bot:latest
    environment:
      ps_url: "postgresql+psycopg://postgres:postgres@db:5432/postgres"
      testps_url: "postgresql+psycopg://postgres:postgres@db:5432/postgres"
      token: $token
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:15.3-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 1s
      timeout: 5s
      retries: 5
  redis:
    image: "redis:alpine"
    restart: always
    ports:
      - "6379:6379"
    volumes:
     - $PWD/redis-data:/var/lib/redis
    environment:
     - REDIS_REPLICATION_MODE=master
